server:
  port: 8762

spring:
  application:
    name: 'discovery'
  profiles:
    active: peer2

eureka:
  instance:
    hostname: peer2
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 90 #default
    leaseRenewalIntervalInSeconds: 30    #default
    metadataMap:
          instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
      registerWithEureka: true
      fetchRegistry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/